In [2]:
import pandas as pd
import numpy as np

In [3]:
#SE DEFINE UNA RED NEURONAL CON LAS SIGUIENTES CARACTERÍSTICAS

#1. Una capa de entrada con dos inputs, x1 y x2.
#2. Una capa oculta con 4 neuronas h1, h2, h3 y h4.
#3. Una capa de salida con 1 neurona o1.

In [4]:
#Inicializar los pesos de las 4 neuronas en la capa oculta
Wxh = np.array([[0.2, 0.65, 0.45, 0.12],
                [0.8, 0.35, 0.55, 0.15]])
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [5]:
#Inicializar los pesos de la neurona en la capa de salida
Why = np.array([[0.2],[0.35],[0.45],[0.52]])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [6]:
#Inicializar los sesgos en la capa oculta
bh = np.array([0.2, 0.15,0.45,0.23])
print(bh)

[0.2  0.15 0.45 0.23]


In [7]:
#Inicializar los sesgos en la capa de salida
by = 0.5

In [8]:
#DEFINIR LA FUNCION SIGMOIDE
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [12]:
def forward_prop(X):
    z1 = np.dot(X, Wxh) + bh #Capa oculta
    a1 = sigmoid(z1) #Capa oculta
    z2 = np.dot(a1, Why) + by
    y_gorro=sigmoid(z2)
    return y_gorro, z1, a1, z2

In [10]:
x = np.array([1.75, 70])

In [13]:
y_gorro = forward_prop(x)
y_gorro

array([0.88288006])

In [14]:
np.dot(x, Wxh) + bh

array([56.55  , 25.7875, 39.7375, 10.94  ])