In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
#Definimos los pesos de las 4 neuronas de la capa oculta
Wxh = np.matrix([[0.67156726, 0.61331638, 0.63982238, 0.71143195, 0.74514822,
       0.13090625, 0.77746792, 0.23132526, 0.54044676, 0.29465683], [0.51537052, 0.41623643, 0.19185848, 0.33693678, 0.50668647,
       0.69245658, 0.0367954 , 0.28318738, 0.8770729 , 0.5546507 ]])

In [18]:
#Inicializar los sesgos en la capa oculta
bh = np.matrix([[0.73693248, 0.46990672, 0.26472259, 0.04647866, 0.88465974,
       0.39038408, 0.36485235, 0.63174467, 0.82516174, 0.58480591]])

In [19]:
#Definimos los pesos de la neurona de salida
#Inicializar los pesos de la neurona en la capa de salida
Why = np.matrix([[0.4183924] , [0.12694562], [0.1162191] , [0.85895327], [0.49153507],
       [0.63967536], [0.76312259], [0.70511683], [0.35286151], [0.15917816]])

In [20]:
#Inicializar los sesgos en la capa de salida
by = np.matrix([0.27138427])

In [21]:
#Función sigmoide
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [22]:
def sigmoidPrime(x):
   return np.exp(-x) / np.multiply(1 + np.exp(-x), 1 + np.exp(-x))

In [23]:
def forward_prop(X):
    z1 = np.dot(X, Wxh) + bh #Capa oculta
    a1 = sigmoid(z1) #Capa oculta
    z2 = np.dot(a1, Why) + by
    y_gorro=sigmoid(z2)
    return y_gorro, z1, a1, z2

In [24]:
stepsizex = 0
stepsizey = 0

In [ ]:
x = np.matrix([85, 80])

In [31]:
def backword_prop(y_hat, z1, a1, z2,alpha):
    global Wxh, Why, intento, stepsizex, stepsizey, seguir
    intento = intento + 1
    delta2 = np.multiply(-(90 - y_hat), sigmoidPrime(z2))
    dJ_dWhy = np.dot(a1.T, delta2)
    delta1 = np.multiply(np.dot(delta2, Why.T), sigmoidPrime(z1))
    dJ_dWxh = np.dot(x.T, delta1)
    stepsizex = alpha * dJ_dWxh
    stepsizey = alpha * dJ_dWhy
    Wxh = Wxh - alpha * dJ_dWxh
    Why = Why - alpha * dJ_dWhy
    seguir = not(intento > 3)
    return Wxh, Why, stepsizex, stepsizey, seguir, intento

In [32]:
intento = 0
seguir = True
alpha = 0.025
while(seguir):
    y_hat, z1, a1, z2 = forward_prop(x)
    backword_prop(y_hat, z1, a1, z2, alpha)
    print(Wxh)
    print(Why)

[[0.67156726 0.61331638 0.63982238 0.71143195 0.74514822 0.13090625
  0.77746792 0.23132526 0.54044676 0.29465683]
 [0.51537052 0.41623643 0.19185848 0.33693678 0.50668647 0.69245658
  0.0367954  0.28318738 0.8770729  0.5546507 ]]
[[0.48097114]
 [0.18952436]
 [0.17879784]
 [0.92153201]
 [0.55411381]
 [0.7022541 ]
 [0.82570133]
 [0.76769557]
 [0.41544025]
 [0.2217569 ]]
[[0.67156726 0.61331638 0.63982238 0.71143195 0.74514822 0.13090625
  0.77746792 0.23132526 0.54044676 0.29465683]
 [0.51537052 0.41623643 0.19185848 0.33693678 0.50668647 0.69245658
  0.0367954  0.28318738 0.8770729  0.5546507 ]]
[[0.48973347]
 [0.19828669]
 [0.18756017]
 [0.93029434]
 [0.56287614]
 [0.71101643]
 [0.83446366]
 [0.7764579 ]
 [0.42420258]
 [0.23051923]]
[[0.67156726 0.61331638 0.63982238 0.71143195 0.74514822 0.13090625
  0.77746792 0.23132526 0.54044676 0.29465683]
 [0.51537052 0.41623643 0.19185848 0.33693678 0.50668647 0.69245658
  0.0367954  0.28318738 0.8770729  0.5546507 ]]
[[0.497766  ]
 [0.2063192

In [28]:
print(Wxh)

[[0.67156726 0.61331638 0.63982238 0.71143195 0.74514822 0.13090625
  0.77746792 0.23132526 0.54044676 0.29465683]
 [0.51537052 0.41623643 0.19185848 0.33693678 0.50668647 0.69245658
  0.0367954  0.28318738 0.8770729  0.5546507 ]]


In [29]:
print(Why)

[[0.47132959]
 [0.17988281]
 [0.16915629]
 [0.91189046]
 [0.54447226]
 [0.69261255]
 [0.81605978]
 [0.75805402]
 [0.4057987 ]
 [0.21211535]]


In [30]:
y_hat

matrix([[0.9951578]])